disk_space_gb: 200
gpu_type: NVIDIA A100 80GB PCIe
num_gpus: 1
network_volume_id: {your_volume_id}
pod_name: My-Project
requirements_file: /workspace/my-project/requirements.txt
template_id: runpod-torch-v280
venv_path: /tmp/venv
vscode_extensions:
  - ms-python.python
